### ISSUE TITLE
Defcon mode should use ephemeral WebKit session

### ISSUE THREAD

**Issue by mcatanzaro** [sidus-dev/poseidon#1]
A friendly heads-up: WebKitGTK+ is going to grow a real private browsing mode with several advantages over attempting to implement it at the web browser level, which is not really possible to do correctly. See for details:

https://lists.webkit.org/pipermail/webkit-gtk/2017-January/002894.html

You will want to use this in poseidon once the API becomes available (most likely in WebKitGTK+ 2.16).

**Comment by sidus-dev** [comment]
Thank you for the hint! I will undoubtedly look for it.
