### ISSUE TITLE
Shortcut for jumping in adressbar

### ISSUE THREAD

**Issue by ukedk** [sidus-dev/poseidon#11]
Hello Andrea! The new  0.6.5 looks great. Thanks. One thing: is it possible to jump via shurtcut to the adressbar ? (like ctrl + l in FF e.g.) ? I tried several ctrl-combinations but no success.
Thank you! Ulrich

**Comment by ukedk** [comment]
I take a look at poseidon.py perhaps it would make sense to set the extension to another shortcut as ctrl + l (most browsers seems to use that for accessing the addressbar)
So what do you think about
Gdk.KEY_e: self.view_plugins,
Gdk.KEY_l: self.tabs[self.current_page][0].main_url_entry.grab_focus,

**Comment by sidus-dev** [comment]
Hi there! Sorry for the delay in replying, I have been very busy the last few days.
I have made some changes in the latest version (0.6.6) and you are correct, but for view_plugins I have set KEY_b, I have already set KEY_e for an experimental feature (not public at the moment and only present in a development version). Thanks for your hints! :+1:
