### ISSUE TITLE
Full screen videos are invisible in full screen mode

### ISSUE THREAD

**Issue by City-busz** [sidus-dev/poseidon#13]
Steps to reproduce:
1. Enter into full screen mode with F11.
2. Play a video (e.g. on YouTube)
3. Switch the video to full screen.

See that the video is invisible while the browser window is unfocused and empty.

**Comment by sidus-dev** [comment]
It works fine here. Tested on Arch, Debian and Fedora with different Python and WebKit versions. Do you have some more info or a screenshot?

**Comment by City-busz** [comment]
It looks like it's a bug in metacity window manager, because it places the full screen video below the browser window. Using Alt+Tab I can see the video.
