### ISSUE TITLE
Update the C code used to load the Python WebExtension

### ISSUE THREAD

**Issue by aperezdc** [sidus-dev/poseidon#2]
Hi there! Just a quick heads up: I have noticed that the you have in [lib/src/extension.c](https://github.com/sidus-dev/poseidon/blob/master/lib/src/extension.c) resembles an older version of my [Python extension loader](https://github.com/aperezdc/webkit2gtk-python-webextension-example/blob/master/pythonloader.c). That's cool and perfectly fine —no problem there—, but if you ever need to pass data serialized in a `GVariant`  from the UI Process to the Web Process, you may want to update to the newest version, which handles that just fine, and fixed a few issues.

Feel free to ping me if you ever run into trouble with the Python WebExtension loader, it's cool that people are using it out there in the wild, and I'll be happy to help.

**Comment by sidus-dev** [comment]
Hi! I love your script, has helped me alot to understand how to deal with web extensions. Thanks for your effort in improving it, I will check the new version ASAP.
