### ISSUE TITLE
Debian Python Error

### ISSUE THREAD

**Issue by beli3ver** [sidus-dev/poseidon#6]
Hi,

tried to use poseidon, but I get this error all the time:

```bash
malte@DebLep:~/poseidon$ ./poseidon
Traceback (most recent call last):
  File "./poseidon.py", line 22, in <module>
    gi.require_version('GtkSource', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 118, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GtkSource not available
malte@DebLep:~/poseidon$
```
Could you help me?

Thanks

**Comment by sidus-dev** [comment]
Hi there,

what distro are you using? Actually seems you need to install [GtkSourceView 3](https://wiki.gnome.org/Projects/GtkSourceView).

**Comment by sidus-dev** [comment]
It's a missing dependency:

`# apt install gir1.2-gtksource-3.0`

Closing issue.
