### ISSUE TITLE
ctrl+click should open in a new tab

### ISSUE THREAD

**Issue by motherload** [sidus-dev/poseidon#8]
As the title says, ctrl+click should open in a new tab but it doesn't. Also, maybe there could be some config options for choosing to open in the background by default.

**Comment by sidus-dev** [comment]
+1 for your tips.

Now (https://github.com/sidus-dev/poseidon/commit/b6510e0b2b82994703f0492ca8276ff9ca687af1) ctrl+click should do the job and I have set a new option in 'settings -> advanced tab' called 'Links Policy' which gives you the chance to force links opening in a new tab. Anyway, enabling this could results in some bad repercussions if a link is javascript.
