### ISSUE TITLE
autofill http(s) in  address-bar ?

### ISSUE THREAD

**Issue by ukedk** [sidus-dev/poseidon#9]
Thanks for this nice Browser which runs very fine on older hardware too. One thing I miss extremly: the autofill of http(s)://
E.g. typing heise.de does not open http(s)://heise.de
I searched in the settings but did not find anything. Is there a possibility to activate this ? 
Thank you !
best regards
Ulrich

**Comment by sidus-dev** [comment]
Thanks, glad you like it!
I will implement this feature in the next update (0.6.5) so since then I'll leave this issue open.

**Comment by sidus-dev** [comment]
A new release is out and you can find a new feature called "HTTPS redirect" in "settings > advanced", just set it to "True" to activate it and restart Poseidon.
